services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri_here

  - type: web
    name: chatbot
    env: python
    buildCommand: cd chatbot && pip install -r requirements.txt
    startCommand: cd chatbot && python app.py
    envVars:
      - key: FLASK_ENV
        value: production

  - type: static
    name: frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://your-backend.onrender.com
